apiVersion: v1
kind: Pod
metadata: 
  name: ibankingsafepod
spec:
  containers:
    - name: ibankingsafe
      image: mohammadali222/ibankingsafe
      ports:
        - name: tomcatport
          containerPort: 8082
          protocol: TCP
      readinessProbe:
        httpGet: 
          port: 8082
          path: /actuator/health/readiness
        initialDelaySeconds: 15
        timeoutSeconds: 15
        failureThreshold: 3
      livenessProbe:
        httpGet: 
          port: 8082
          path: /actuator/health/liveness
        initialDelaySeconds: 15
        timeoutSeconds: 15
        failureThreshold: 3    
      env:
        - name: "db.username"
          valueFrom:
            secretKeyRef:
              name: ibankingsafesecret
              key:  username 
        - name: "db.password"
          valueFrom:
            secretKeyRef:
              name: ibankingsafesecret
              key: password       

              
